stages:
  - install
  - lint
  - unit-tests
  - functional-tests
  - integration-tests
  - create-resolve-app-tests
  - clear
  
macOS (install):
  stage: install
  script:
    - echo macos
    
ubuntu (install):
  stage: install
  script:
    - echo ubuntu
    
windows (install):
  stage: install
  script:
    - echo windows

eslint:
  stage: lint
  script:
    - echo eslint
   
prettier-check:
  stage: lint
  script:
    - echo prettier-check
    
macOS (unit-tests):
  stage: unit-tests
  script:
    - echo macos
    
ubuntu (unit-tests):
  stage: unit-tests
  script:
    - echo ubuntu
    
windows (unit-tests):
  stage: unit-tests
  script:
    - echo windows
    
macOS (functional-tests):
  stage: functional-tests
  script:
    - echo macos
    
ubuntu (functional-tests):
  stage: functional-tests
  script:
    - echo ubuntu
    
windows (functional-tests):
  stage: functional-tests
  script:
    - echo windows
    
bus:
  stage: integration-tests
  script:
    - echo (memory, rabbitmq, zeromq)

storage:
  stage: integration-tests
  script:
    - echo (memory, mongodb, mysql, dynamodb)
    
readmodel-adapter:
  stage: integration-tests
  script:
    - echo (memory, mongodb, mysql)         
    
subscribe-adapters:
  stage: integration-tests
  script:
    - echo (mqtt, socket.io)
    
npx create-resolve-app:
  stage: create-resolve-app-tests
  script:
    - echo npx
    
yarn create resolve-app:
  stage: create-resolve-app-tests
  script:
    - echo yarn
    
macOS (clear):
  stage: clear
  script:
    - echo macos
    
ubuntu (clear):
  stage: clear
  script:
    - echo ubuntu
    
windows (clear):
  stage: clear
  script:
    - echo windows
